"""initial migration

Revision ID: 17de2eab54fd
Revises: 
Create Date: 2026-08-11 19:30:27.292786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17de2eab54fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0 AND size_bytes <= (2 * 1024 * 1024)', name='check_size_positive_and_in_limit'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('technologies', sa.String(length=150), nullable=True),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=True),
    sa.Column('offered_salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('offered_salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('job_posting_url', sa.String(), nullable=True),
    sa.Column('source_platform', sa.String(length=100), nullable=True),
    sa.Column('applied_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('saved', 'applied', 'screening', 'interview', 'technical_test', 'offer', 'rejected', 'withdrawn', name='status_enum'), nullable=False),
    sa.CheckConstraint('(expected_salary_min IS NULL OR expected_salary_min >= 0) AND (expected_salary_max IS NULL OR expected_salary_max >= 0) AND (expected_salary_min IS NULL OR expected_salary_max IS NULL OR expected_salary_min <= expected_salary_max)', name='check_expected_salary'),
    sa.CheckConstraint('(offered_salary_min IS NULL OR offered_salary_min >= 0) AND (offered_salary_max IS NULL OR offered_salary_max >= 0) AND (offered_salary_min IS NULL OR offered_salary_max IS NULL OR offered_salary_min <= offered_salary_max)', name='check_offered_salary'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_table('users')
    op.drop_table('answers')
    # ### end Alembic commands ###
