"""add google id

Revision ID: ab138563e105
Revises: e116c58e293b
Create Date: 2026-09-02 07:10:11.226487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab138563e105'
down_revision: Union[str, Sequence[str], None] = 'e116c58e293b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_foreign_key('fk_application_user_id_users', 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint('unique_users_google_id', 'users', ['google_id'])
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_users_google_id', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'google_id')
    op.drop_constraint('fk_application_user_id_users', 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_column('applications', 'user_id')
    # ### end Alembic commands ###
