"""increase application technologies length

Revision ID: e116c58e293b
Revises: 17de2eab54fd
Create Date: 2026-08-21 15:41:48.654581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e116c58e293b'
down_revision: Union[str, Sequence[str], None] = '17de2eab54fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'technologies',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'technologies',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###
